### PR TITLE
added Feature/eslint fix push ci

### PR DESCRIPTION
**Pull request by Raboro**
Added scripts to to package.json to run Eslinter.
Added CI file to use linter with GH action bot to push fixes via CI in repo.
Already fixed issues. But not all could be solved directly by the linter, they must be fixed manually. As long as those are not fixed the build fails. #44

### CODE REVIEW

**Comment by Raboro** [comment]
Do you know how to fix the signing problem with the commits, which is blocking the merging?

**Comment by Leonezz** [comment]
Yes I will handle it.

**Comment by Leonezz** [comment]
Hi @Raboro , sorry to bother but it seems there is an issue with the newly added eslint action, see https://github.com/Leonezz/obsidian-tasks-calendar-wrapper/actions/runs/5450752456/jobs/9916327976 for details.

**Comment by Leonezz** [comment]
Oh I get it, does it mean that those issues are not auto fixable thus I need to fix them manually?

**Comment by Raboro** [comment]
Yes your right. Eslint can fix a lot of issues automatically but not all of them. I implemented the CI that first Eslint tries to fix the issues, if there are some issues. Those fixes are getting pushed into the repo and after that Eslint checks again if there are some issues left.

**Comment by Leonezz** [comment]
Got it, I will fix the remaining issues soon.

**Comment by Raboro** [comment]
Great, thanks for the nice cooperation.

**Comment by Leonezz** [comment]
Thanks for your great work too! Didn't realize there are so many inappropriate code in this project, luckily it worked now!

**Pull request merged**
